#Base containers
services:
  postgres:
    image: 'postgres:16'
    container_name: collectto_db
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: collectto_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ORACLE_TENANT_ID=${ORACLE_TENANT_ID}
      - ORACLE_USER_ID=${ORACLE_USER_ID}
      - ORACLE_FINGERPRINT=${ORACLE_FINGERPRINT}
      - ORACLE_REGION=${ORACLE_REGION}
      - ORACLE_NAMESPACE=${ORACLE_NAMESPACE}
      - ORACLE_BUCKET=${ORACLE_BUCKET}
      - ORACLE_PRIVATE_KEY=${ORACLE_PRIVATE_KEY}