ALTER TABLE users 
ADD COLUMN deactivated_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE collections 
ADD COLUMN deactivated_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE items 
ADD COLUMN deactivated_at TIMESTAMPTZ DEFAULT NULL;